#!/bin/bash
archive_name=psutils-p17.tar.gz
tar xzf $archive_name
rm psutils/fixmacps*
rm psutils/md68_0.ps
rm psutils/md71_0.ps
patch -p0 < psutils-copyright.patch
tar czf $archive_name psutils/
rm -r psutils/
